### ISSUE TITLE
执行 go 脚本时报错

### ISSUE THREAD

**Issue by includeleec** [virushuo/mixin-node#8]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4e53f9]
goroutine 1 [running]:
main.main()
        D:/0-Blockchain/mixin/mixin-node/tools/decryptkey.go:32 +0x119
exit status 2

**Comment by huo-ju** [comment]
这个错误在32行，ParsePKCS1PrivateKey 这个是go本身的方法，按说不应该出错。唯一可能性是没找到密钥地址，主要是我们没有在windows直接用golang测试过…所以可以试试看在其他平台吗？
